# Generated by Django 3.1.2 on 2020-10-11 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='surname',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
