# Generated by Django 3.1.2 on 2020-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0002_greeting_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban_benef', models.TextField()),
                ('causale', models.TextField()),
                ('importo', models.IntegerField()),
            ],
        ),
    ]
