# Generated by Django 3.1.2 on 2020-11-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0003_dario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataMovimento', models.DateTimeField()),
                ('causale', models.TextField()),
                ('importo', models.IntegerField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dario',
        ),
    ]
