# Generated by Django 3.1.2 on 2020-11-22 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0004_auto_20201122_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentoone',
            old_name='dataMovimento',
            new_name='datamov',
        ),
    ]
