# Generated by Django 3.1.2 on 2020-11-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0005_auto_20201122_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoone',
            name='datamov',
            field=models.DateField(),
        ),
    ]
