# Generated by Django 3.1.2 on 2020-11-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0006_auto_20201123_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoOneHistogram',
            fields=[
                ('datamov', models.DateField()),
                ('importo', models.IntegerField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'greetings_movimentoonehistogram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimentoOneLine',
            fields=[
                ('datamov', models.DateField()),
                ('importo', models.IntegerField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'greetings_movimentooneline',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS greetings_movimentoonehistogram;
           
            """
        ),
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS greetings_movimentooneline;
            
            """
        )
    ]
