# Generated by Django 3.1.2 on 2020-11-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0006_auto_20201123_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoOneHistogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datamov', models.DateField()),
                ('importo', models.IntegerField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'greetings_movimentoonehistogram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimentoOneLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datamov', models.DateField()),
                ('importo', models.IntegerField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'greetings_movimentooneline',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS greetings_movimentoonehistogram;
            CREATE OR REPLACE VIEW greetings_movimentoonehistogram as
            select datamov, email, sum(importo) as importo from greetings_movimentoone group by datamov,email order by datamov;
            """
        ),
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS greetings_movimentooneline;
            CREATE OR REPLACE VIEW greetings_movimentooneline as
            select datamov, email, (select COALESCE(sum(importo),0) as importo from greetings_movimentoone where datamov<movim.datamov and email = movim.email) from greetings_movimentoone as movim group by datamov,email order by datamov;
            """
        )
    ]
