# Generated by Django 3.1.2 on 2020-11-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0007_movimentoonehistogram_movimentooneline'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoHistogramOne',
            fields=[
                ('id', models.DateField(verbose_name='ID')),
                ('datamov', models.DateField()),
                ('importo', models.IntegerField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'greetings_movimentohistogramone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimentoLineOne',
            fields=[
                ('id', models.DateField(verbose_name='ID')),
                ('datamov', models.DateField()),
                ('importo', models.IntegerField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'greetings_movimentolineone',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MovimentoOneHistogram',
        ),
        migrations.DeleteModel(
            name='MovimentoOneLine',
        ),
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS greetings_movimentolineone;
            DROP VIEW IF EXISTS greetings_movimentohistogramone;

            CREATE OR REPLACE VIEW greetings_movimentohistogramtwo as
            select distinct(cast(date_trunc('month', datamov) as date)) as datamov2, email, sum(importo) as importo from greetings_movimentoone group by datamov2, email order by datamov2;
            
            CREATE OR REPLACE VIEW greetings_movimentohistogramone as
            select datamov2 as id, datamov2 as datamov, email, importo from greetings_movimentohistogramtwo;

            CREATE OR REPLACE VIEW greetings_movimentolineone as
            select distinct(datamov) as id, datamov as datamov, email, (select COALESCE(sum(importo),0) as importo from greetings_movimentohistogramone where datamov<movim.datamov and email = movim.email) from greetings_movimentohistogramone as movim group by id, datamov,email order by datamov;
           
            
            """
        )
    ]
