# Generated by Django 3.1.2 on 2020-12-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0008_auto_20201123_1806'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS greetings_movimentolineone;
            DROP VIEW IF EXISTS greetings_movimentohistogramone;
        """
        ),
        migrations.AlterField(
            model_name='movimentoone',
            name='importo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        )
        
    ]
